# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n_qhZ3Vp2FEL_rREMVNWzAaJHo8DGHzt
"""
from huggingface_hub import hf_hub_download
import gradio as gr
import pandas as pd
import numpy as np
import zipfile
import re
from pathlib import Path
from typing import Tuple, Dict, Optional
from functools import lru_cache

# =========================
# IMDb index (preprocessed parquet)
# =========================
from huggingface_hub import hf_hub_download

IMDB_PATH = Path(
    hf_hub_download(
        repo_id="celalibr/letterboxd-imdb-index",
        filename="imdb_index.parquet",
        repo_type="dataset"
    )
)

def normalize_title_full(s: str) -> str:
    """Normalize titles for matching: lowercase, remove punctuation, normalize spaces."""
    s = str(s).lower().strip()
    s = re.sub(r"[^a-z0-9\s]", "", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s


@lru_cache(maxsize=1)
def load_imdb_index() -> pd.DataFrame:
    """Load IMDb parquet once per container lifecycle."""
    imdb = pd.read_parquet(IMDB_PATH)

    # Ensure numeric
    imdb["startYear"] = pd.to_numeric(imdb.get("startYear"), errors="coerce")
    imdb["averageRating"] = pd.to_numeric(imdb.get("averageRating"), errors="coerce")
    imdb["numVotes"] = pd.to_numeric(imdb.get("numVotes"), errors="coerce")
    if "runtimeMinutes" in imdb.columns:
        imdb["runtimeMinutes"] = pd.to_numeric(imdb.get("runtimeMinutes"), errors="coerce")

    # Add normalized title if missing
    if "primary_norm" not in imdb.columns:
        if "primaryTitle" not in imdb.columns:
            raise ValueError("IMDb parquet must contain 'primaryTitle' column.")
        imdb["primary_norm"] = imdb["primaryTitle"].astype(str).apply(normalize_title_full)

    return imdb


@lru_cache(maxsize=1)
def build_imdb_lookup() -> pd.DataFrame:
    """
    Build a unique lookup:
      (primary_norm, startYear) -> best IMDb row (highest numVotes when duplicates exist)
    Stored as a multi-indexed DataFrame for fast join.
    """
    imdb = load_imdb_index()
    imdb2 = imdb.dropna(subset=["startYear"]).copy()
    imdb2 = imdb2.sort_values("numVotes", ascending=False)
    lookup = (
        imdb2.drop_duplicates(subset=["primary_norm", "startYear"])
        .set_index(["primary_norm", "startYear"])
    )
    return lookup


# =========================
# Letterboxd ZIP readers
# =========================
def read_csv_from_zip(zip_path: Path, filename: str) -> Optional[pd.DataFrame]:
    """Read a CSV by suffix match from Letterboxd export ZIP."""
    with zipfile.ZipFile(zip_path, "r") as z:
        members = [m for m in z.namelist() if m.lower().endswith(filename.lower())]
        if not members:
            return None
        with z.open(members[0]) as f:
            return pd.read_csv(f)


def build_user_df_from_zip(zip_path: Path, neutral_rating: float = 3.0) -> pd.DataFrame:
    """
    Returns a dataframe with:
      film, rating (NaN if unrated), rating_model (rating filled with neutral), watched(True), rated(True/False)

    - ratings.csv supplies rated films
    - watched.csv supplies watched films (may be unrated)
    """
    ratings = read_csv_from_zip(zip_path, "ratings.csv")
    watched = read_csv_from_zip(zip_path, "watched.csv")
    if ratings is None or watched is None:
        raise ValueError("ZIP must contain ratings.csv and watched.csv")

    for col in ["Name", "Year"]:
        if col not in watched.columns:
            raise ValueError(f"watched.csv missing column: {col}")
    for col in ["Name", "Year", "Rating"]:
        if col not in ratings.columns:
            raise ValueError(f"ratings.csv missing column: {col}")

    ratings = ratings.copy()
    watched = watched.copy()

    ratings["film"] = ratings["Name"].astype(str) + " (" + ratings["Year"].astype(int).astype(str) + ")"
    watched["film"] = watched["Name"].astype(str) + " (" + watched["Year"].astype(int).astype(str) + ")"

    # Rated
    ratings_clean = ratings[["film", "Rating"]].rename(columns={"Rating": "rating"}).dropna()
    ratings_clean["rating"] = pd.to_numeric(ratings_clean["rating"], errors="coerce")
    ratings_clean = ratings_clean.dropna(subset=["rating"])
    ratings_clean["watched"] = True
    ratings_clean["rated"] = True

    # Watched but unrated -> rating stays NaN (DISPLAY), but rating_model will fill neutral (SCORING)
    watched_only = watched[~watched["film"].isin(ratings_clean["film"])].copy()
    watched_only["rating"] = np.nan
    watched_only = watched_only[["film", "rating"]]
    watched_only["watched"] = True
    watched_only["rated"] = False

    user_df = pd.concat([ratings_clean, watched_only], ignore_index=True).reset_index(drop=True)
    user_df["rating_model"] = user_df["rating"].fillna(float(neutral_rating))
    return user_df


# =========================
# Matching helpers
# =========================
def split_title_year(film_key: str) -> Tuple[str, float]:
    """Split 'Title (YYYY)' into (Title, YYYY)."""
    m = re.match(r"^(.*)\s+\((\d{4})\)\s*$", str(film_key))
    if not m:
        return str(film_key), np.nan
    return m.group(1), float(m.group(2))


def prepare_user(df: pd.DataFrame) -> pd.DataFrame:
    """Add title, year, title_norm columns to user dataframe."""
    out = df.copy()
    ty = out["film"].apply(split_title_year)
    out["title"] = ty.apply(lambda x: x[0])
    out["year"] = ty.apply(lambda x: x[1])
    out["title_norm"] = out["title"].astype(str).apply(normalize_title_full)
    return out


def attach_imdb(user_df: pd.DataFrame) -> pd.DataFrame:
    """Join user films to IMDb by (title_norm, year)."""
    u = prepare_user(user_df)
    lookup = build_imdb_lookup()
    u = u.join(lookup, on=["title_norm", "year"], rsuffix="_imdb")
    return u


# =========================
# Similarity / compatibility
# =========================
def jaccard_overlap(df1: pd.DataFrame, df2: pd.DataFrame) -> float:
    s1, s2 = set(df1["film"]), set(df2["film"])
    if len(s1 | s2) == 0:
        return 0.0
    return len(s1 & s2) / len(s1 | s2)


def pearson_corr_common(df1: pd.DataFrame, df2: pd.DataFrame, min_common: int = 5):
    merged = df1.merge(df2, on="film", suffixes=("_u1", "_u2"))
    # Use rating_model for compatibility math
    merged = merged.dropna(subset=["rating_model_u1", "rating_model_u2"])
    if len(merged) < min_common:
        return 0.0, merged
    corr = np.corrcoef(merged["rating_model_u1"], merged["rating_model_u2"])[0, 1]
    if np.isnan(corr):
        corr = 0.0
    return float(max(corr, 0.0)), merged


def mad_norm(merged: pd.DataFrame) -> float:
    """Mean absolute rating difference normalized by 5 (uses rating_model)."""
    if len(merged) == 0:
        return 1.0
    diff = np.mean(np.abs(merged["rating_model_u1"] - merged["rating_model_u2"]))
    return float(diff / 5.0)


def compatibility_score(df1: pd.DataFrame, df2: pd.DataFrame):
    overlap = jaccard_overlap(df1, df2)
    corr, merged = pearson_corr_common(df1, df2)
    mad = mad_norm(merged)

    score = 0.35 * overlap + 0.45 * corr + 0.20 * (1 - mad)
    return float(score), {
        "overlap": overlap,
        "corr": corr,
        "mad_norm": mad,
        "common_films": len(merged),
    }


def match_label(score_0_1: float) -> str:
    s = float(np.clip(score_0_1, 0.0, 1.0))
    if s < 0.33:
        return "Low match"
    elif s < 0.66:
        return "Medium match"
    return "High match"


def badge_style(label: str) -> str:
    if label.startswith("Low"):
        return "background: rgba(239,68,68,0.15); border: 1px solid rgba(239,68,68,0.35); color:#fecaca;"
    if label.startswith("Medium"):
        return "background: rgba(234,179,8,0.15); border: 1px solid rgba(234,179,8,0.35); color:#fde68a;"
    return "background: rgba(34,197,94,0.15); border: 1px solid rgba(34,197,94,0.35); color:#bbf7d0;"


# =========================
# Recommendation scoring
# =========================
MOOD_PRESETS = {
    "romantic": {"Romance": 1.4, "Drama": 1.2},
    "fun": {"Comedy": 1.5, "Adventure": 1.2},
    "dark": {"Thriller": 1.4, "Horror": 1.3},
    "epic": {"Action": 1.4, "Fantasy": 1.3},
}


def genre_profile_from_meta(user_meta: pd.DataFrame, like_threshold: float = 4.0) -> pd.Series:
    # Use rating_model for consistent scoring even if unrated
    liked = user_meta[user_meta["rating_model"] >= like_threshold].copy()
    liked = liked.dropna(subset=["genres"])
    g = liked["genres"].astype(str).str.split(",").explode()
    return g.value_counts(normalize=True)


def apply_mood(genre_dist: pd.Series, mood: Optional[str]) -> pd.Series:
    g = genre_dist.copy()
    if mood and mood in MOOD_PRESETS:
        for k, v in MOOD_PRESETS[mood].items():
            if k in g.index:
                g.loc[k] *= v
    s = g.sum()
    return g / (s if s else 1.0)


def harmonic(a: float, b: float) -> float:
    return 2 * a * b / (a + b + 1e-9)


def exploration_bonus(numVotes: float) -> float:
    if pd.isna(numVotes):
        return 0.0
    v = float(numVotes)
    if v < 20000:
        return 0.05
    elif v < 100000:
        return 0.02
    return 0.0


def score_for_user(
    genres_str: str,
    imdb_rating: float,
    numVotes: float,
    user_genre: pd.Series,
    min_votes: int = 5000,
) -> float:
    gs = str(genres_str).split(",") if pd.notna(genres_str) else []
    genre_score = float(user_genre.reindex(gs).fillna(0).sum())

    if pd.isna(imdb_rating):
        quality = 0.0
    else:
        reliability = 1.0 if (pd.notna(numVotes) and float(numVotes) >= min_votes) else 0.6
        quality = (float(imdb_rating) / 10.0) * reliability

    return 0.75 * genre_score + 0.25 * quality


def genre_set(genres_str: str) -> set:
    return set(str(genres_str).split(",")) if pd.notna(genres_str) else set()


def jaccard(a: set, b: set) -> float:
    if not a and not b:
        return 0.0
    return len(a & b) / len(a | b)


def year_diversity_bonus(selected_years, cand_year) -> float:
    if not selected_years:
        return 0.0
    years = [y for y in selected_years if pd.notna(y)]
    if not years or pd.isna(cand_year):
        return 0.0
    avg = float(np.mean(years))
    return abs(float(cand_year) - avg) / 100.0


def mmr_rerank(df: pd.DataFrame, k: int = 10, lambda_: float = 0.78, rel_col: str = "final_rel") -> pd.DataFrame:
    df = df.copy()
    df["gset"] = df["genres"].apply(genre_set)

    selected_rows = []
    selected_years = []
    candidates = df.sort_values(rel_col, ascending=False).to_dict("records")

    while len(selected_rows) < k and candidates:
        best_idx, best_score = None, -1e9

        for i, cand in enumerate(candidates):
            rel = float(cand.get(rel_col, 0.0))
            cand_g = cand["gset"]
            cand_y = cand.get("startYear", np.nan)

            if not selected_rows:
                div_pen = 0.0
            else:
                sims = [jaccard(cand_g, s["gset"]) for s in selected_rows]
                div_pen = max(sims)

            y_bonus = year_diversity_bonus(selected_years, cand_y)

            mmr = lambda_ * rel - (1 - lambda_) * div_pen + 0.05 * y_bonus
            if mmr > best_score:
                best_score = mmr
                best_idx = i

        chosen = candidates.pop(best_idx)
        selected_rows.append(chosen)
        selected_years.append(chosen.get("startYear", np.nan))

    out = pd.DataFrame(selected_rows).drop(columns=["gset"])
    return out


# =========================
# Main pipeline
# =========================
def compute_all(zip1_file: str, zip2_file: str):
    zip1 = Path(zip1_file)
    zip2 = Path(zip2_file)

    user1 = build_user_df_from_zip(zip1)
    user2 = build_user_df_from_zip(zip2)

    user1m = attach_imdb(user1)
    user2m = attach_imdb(user2)

    match1 = float(user1m["tconst"].notna().mean()) if "tconst" in user1m.columns else 0.0
    match2 = float(user2m["tconst"].notna().mean()) if "tconst" in user2m.columns else 0.0

    comp, details = compatibility_score(user1, user2)

    # ---------- SHARED TOP 20 (both watched + both rated, sorted by avg rating) ----------
    shared = user1.merge(user2, on="film", suffixes=("_u1", "_u2"))
    shared["avg_real_rating"] = (shared["rating_u1"] + shared["rating_u2"]) / 2

    # Only keep where both have REAL ratings (not NaN)
    shared_top = shared.dropna(subset=["rating_u1", "rating_u2"]).copy()

    # Attach IMDb rating
    shared_p = prepare_user(shared_top[["film"]].copy())
    lookup = build_imdb_lookup()
    shared_meta = shared_p.join(lookup, on=["title_norm", "year"])
    shared_top["imdb_rating"] = shared_meta.get("averageRating")

    shared_top = shared_top.sort_values("avg_real_rating", ascending=False).head(20).reset_index(drop=True)

    shared_top_out = shared_top[["film", "imdb_rating", "rating_u1", "rating_u2"]].copy()
    shared_top_out = shared_top_out.rename(
        columns={
            "film": "FILM",
            "imdb_rating": "IMDB",
            "rating_u1": "USER1 RATING",
            "rating_u2": "USER2 RATING",
        }
    )

    # ---------- ONE WATCHED, OTHER DIDN'T (outer merge on union) ----------
    u1 = user1[["film", "rating"]].rename(columns={"rating": "rating_u1"})
    u2 = user2[["film", "rating"]].rename(columns={"rating": "rating_u2"})
    union = u1.merge(u2, on="film", how="outer")

    # Attach IMDb rating
    union_p = prepare_user(union[["film"]].copy())
    union_meta = union_p.join(lookup, on=["title_norm", "year"])
    union["imdb_rating"] = union_meta.get("averageRating")

    # Mark who watched
    union["USER1 WATCHED"] = union["rating_u1"].notna()
    union["USER2 WATCHED"] = union["rating_u2"].notna()

    # Show only cases where exactly one watched (xor)
    one_watched = union[(union["USER1 WATCHED"] ^ union["USER2 WATCHED"])].copy()

    # Convert ratings to display "-" if missing
    def disp(x):
        return "-" if pd.isna(x) else float(x)

    one_watched_out = one_watched[["film", "imdb_rating", "rating_u1", "rating_u2", "USER1 WATCHED", "USER2 WATCHED"]].copy()
    one_watched_out["rating_u1"] = one_watched_out["rating_u1"].apply(disp)
    one_watched_out["rating_u2"] = one_watched_out["rating_u2"].apply(disp)

    one_watched_out = one_watched_out.rename(columns={
        "film": "FILM",
        "imdb_rating": "IMDB",
        "rating_u1": "USER1 RATING",
        "rating_u2": "USER2 RATING",
    })

    # Sort: show highest IMDb first (nice UX)
    one_watched_out["IMDB_sort"] = pd.to_numeric(one_watched_out["IMDB"], errors="coerce")
    one_watched_out = one_watched_out.sort_values("IMDB_sort", ascending=False).drop(columns=["IMDB_sort"]).reset_index(drop=True)

    # ---------- Genre table ----------
    g1 = genre_profile_from_meta(user1m)
    g2 = genre_profile_from_meta(user2m)
    all_g = sorted(set(g1.index) | set(g2.index))
    g1n = g1.reindex(all_g).fillna(0)
    g2n = g2.reindex(all_g).fillna(0)
    g1n = g1n / (g1n.sum() or 1)
    g2n = g2n / (g2n.sum() or 1)
    joint = (g1n + g2n) / 2
    joint = joint / (joint.sum() or 1)

    g_df = (
        pd.DataFrame(
            {
                "user1": g1n.sort_values(ascending=False).head(12),
                "user2": g2n.sort_values(ascending=False).head(12),
                "joint": joint.sort_values(ascending=False).head(12),
            }
        )
        .fillna(0)
        .reset_index()
        .rename(columns={"index": "genre"})
    )

    state = {
        "user1": user1,
        "user2": user2,
        "user1m": user1m,
        "user2m": user2m,
        "g1n": g1n,
        "g2n": g2n,
    }

    # ---------- Summary UI ----------
    comp01 = float(np.clip(comp, 0.0, 1.0))
    pct = comp01 * 100
    label = match_label(comp01)
    badge = badge_style(label)

    big = f"""
<div style="text-align:center; padding: 10px 8px; margin-top: 6px;">
  <div style="font-size: 28px; font-weight: 900; color: #22c55e;">
    YOUR SHARED TASTE: {pct:.1f}%
  </div>

  <div style="max-width: 520px; margin: 10px auto 6px auto;">
    <div style="height: 10px; width: 100%; background: rgba(255,255,255,0.10); border-radius: 999px; overflow: hidden;">
      <div style="height: 100%; width: {pct:.1f}%; background: #22c55e;"></div>
    </div>
  </div>

  <div style="display:flex; justify-content:center; gap:10px; align-items:center; margin-top: 6px;">
    <span style="padding: 4px 10px; border-radius: 999px; font-size: 12px; {badge}">
      {label}
    </span>
    <span style="opacity:0.80; font-size: 12px;">
      (based on overlap + rating agreement)
    </span>
  </div>
</div>
"""

    stats = f"""
<div style="margin-top: 8px; padding: 10px 12px; border: 1px solid rgba(255,255,255,0.10); border-radius: 14px;">
  <div style="font-size: 13px; line-height: 1.65; opacity:0.92;">
    <b>Common films:</b> {details['common_films']}<br>
    <b>Overlap (Jaccard):</b> {details['overlap']:.3f}<br>
    <b>Rating agreement (Pearson, clamped):</b> {details['corr']:.3f}<br>
    <b>Mean abs diff (norm):</b> {details['mad_norm']:.3f}<br>
    <b>IMDb match rate:</b> User1 {match1*100:.1f}% | User2 {match2*100:.1f}%
  </div>
</div>
"""
    summary_md = big + stats

    # Download CSV (shared top 20)
    blend_csv_path = Path("/tmp/blend_shared_top20.csv")
    shared_top_out.to_csv(blend_csv_path, index=False)

    return summary_md, shared_top_out, one_watched_out, g_df, str(blend_csv_path), state


def recommend(state: Dict, mood: str, top_k: int):
    imdb = load_imdb_index()

    user1 = state["user1"]
    user2 = state["user2"]
    g1n = state["g1n"]
    g2n = state["g2n"]

    mood_val = None if mood == "none" else mood
    g1m = apply_mood(g1n, mood_val)
    g2m = apply_mood(g2n, mood_val)

    # Unseen by either user (watched set)
    seen = set(user1["film"]) | set(user2["film"])

    cand = imdb.dropna(subset=["startYear", "primaryTitle", "averageRating", "numVotes", "genres"]).copy()
    cand["film"] = cand["primaryTitle"].astype(str) + " (" + cand["startYear"].astype(int).astype(str) + ")"
    cand = cand[~cand["film"].isin(seen)].copy()

    cand = cand[(cand["numVotes"] >= 5000) & (cand["averageRating"] >= 6.5) & (cand["startYear"] >= 1960)].copy()

    cand["score_u1"] = cand.apply(lambda r: score_for_user(r["genres"], r["averageRating"], r["numVotes"], g1m), axis=1)
    cand["score_u2"] = cand.apply(lambda r: score_for_user(r["genres"], r["averageRating"], r["numVotes"], g2m), axis=1)
    cand["couple_score"] = cand.apply(lambda r: harmonic(r["score_u1"], r["score_u2"]), axis=1)
    cand["explore_bonus"] = cand["numVotes"].apply(exploration_bonus)
    cand["final_rel"] = cand["couple_score"] + cand["explore_bonus"]

    top = mmr_rerank(cand, k=int(top_k), lambda_=0.78, rel_col="final_rel")

    if "runtimeMinutes" not in top.columns:
        top["runtimeMinutes"] = np.nan

    # Convert scores to % (0–100) for UI (but NO overall column now)
    def to_pct(x):
        try:
            return float(np.clip(float(x), 0.0, 1.0)) * 100.0
        except Exception:
            return np.nan

    out = top[[
        "film",
        "genres",
        "averageRating",
        "runtimeMinutes",
        "score_u1",
        "score_u2",
        "couple_score",
    ]].copy()

    out["USER1 SCORE (%)"] = out["score_u1"].apply(to_pct)
    out["USER2 SCORE (%)"] = out["score_u2"].apply(to_pct)
    out["COUPLE SCORE (%)"] = out["couple_score"].apply(to_pct)

    out = out.rename(columns={
        "film": "FILM",
        "genres": "GENRE",
        "averageRating": "IMDB",
        "runtimeMinutes": "RUNTIME",
    })

    out_final = out[[
        "FILM",
        "GENRE",
        "IMDB",
        "RUNTIME",
        "USER1 SCORE (%)",
        "USER2 SCORE (%)",
        "COUPLE SCORE (%)",
    ]].copy()

    out_final["IMDB"] = pd.to_numeric(out_final["IMDB"], errors="coerce").round(2)
    for c in ["USER1 SCORE (%)", "USER2 SCORE (%)", "COUPLE SCORE (%)"]:
        out_final[c] = pd.to_numeric(out_final[c], errors="coerce").round(1)
    out_final["RUNTIME"] = pd.to_numeric(out_final["RUNTIME"], errors="coerce")

    rec_csv_path = Path("/tmp/recommendations.csv")
    out_final.to_csv(rec_csv_path, index=False)

    years = out_final["FILM"].str.extract(r"\((\d{4})\)")[0].astype(float)
    year_spread = float(years.max() - years.min()) if years.notna().any() else 0.0

    md = (
        f"### 🎯 Recommendations\n"
        f"- **Mood:** `{mood}`\n"
        f"- **Unique genres:** `{out_final['GENRE'].nunique()}`\n"
        f"- **Year spread:** `{year_spread:.0f}` years\n"
    )

    return md, out_final, str(rec_csv_path)


# =========================
# UI (Gradio)
# =========================
with gr.Blocks(
    title="Letterboxd Blend + Couple Recommender",
    theme=gr.themes.Soft(),
    css="""
    .hero { padding: 12px 14px; border-radius: 18px; border: 1px solid rgba(255,255,255,0.10); }
    .subtle { opacity: 0.85; }
    """
) as demo:
    gr.Markdown(
        """
<div class="hero">
  <h1 style="margin-bottom:6px;">🎬 Letterboxd Blend + Couple Recommender</h1>
  <div class="subtle">Upload two Letterboxd export ZIPs → see overlap + compatibility + mood-based recommendations.</div>
</div>
        """
    )

    state = gr.State(value=None)

    with gr.Tab("Blend"):
        with gr.Row():
            with gr.Column(scale=1, min_width=360):
                zip1 = gr.File(label="User 1 export ZIP", file_types=[".zip"])
                zip2 = gr.File(label="User 2 export ZIP", file_types=[".zip"])
                btn = gr.Button("Compute Blend", variant="primary")
            with gr.Column(scale=2):
                summary = gr.Markdown()

        gr.Markdown("# LETTERBOXD BLEND")

        shared_top20_table = gr.Dataframe(
            label="Top 20 shared (highest average rating — only if both rated)",
            interactive=False
        )

        one_watched_table = gr.Dataframe(
            label="One watched, other didn't (ratings show '-' if not rated/watched)",
            interactive=False
        )

        genre_table = gr.Dataframe(
            label="Top genres (User1 vs User2 vs Joint)",
            interactive=False
        )

        blend_download = gr.File(label="Download shared top 20 CSV")

        def _compute(z1, z2):
            return compute_all(z1.name, z2.name)

        btn.click(
            _compute,
            inputs=[zip1, zip2],
            outputs=[summary, shared_top20_table, one_watched_table, genre_table, blend_download, state],
        )

    with gr.Tab("Recommend"):
        with gr.Row():
            mood = gr.Dropdown(
                choices=["none", "romantic", "fun", "dark", "epic"],
                value="none",
                label="Mood"
            )
            top_k = gr.Slider(5, 25, value=10, step=1, label="Top K")

        btn2 = gr.Button("Recommend", variant="primary")

        gr.Markdown("# RECOMMENDATIONS")

        rec_md = gr.Markdown()
        rec_table = gr.Dataframe(label="Recommendations", interactive=False)
        rec_download = gr.File(label="Download recommendations CSV")

        def _rec(st, mood_val, k):
            if st is None:
                raise gr.Error("First compute Blend (upload zips) to build profiles.")
            return recommend(st, mood_val, int(k))

        btn2.click(_rec, inputs=[state, mood, top_k], outputs=[rec_md, rec_table, rec_download])

demo.launch()
